pipeline:
  identifier: Build_elaverick_certainty_1732371060156
  name: Build certainty
  orgIdentifier: default
  projectIdentifier: Certainty
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1732292412255
        repoName: elaverick/certainty
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installandupdatedeps
                  name: install and update deps
                  spec:
                    shell: Sh
                    command: |-
                      sudo apt-get update
                      sudo apt-get install libgtest-dev libncurses-dev libgpm-dev
                  timeout: ""
                  type: Run
              - step:
                  identifier: cmakebuildmake
                  name: cmake build  make
                  spec:
                    command: mkdir build && cd build && cmake .. && cmake --build .
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
